### PR TITLE
don't disable convert when converting lists

### PR DESCRIPTION
**Pull request by kevinushey**
Fixes the issue described in https://github.com/rstudio/keras/issues/732.

I wanted to add a unit test for this behavior but for the life of me couldn't produce a a standalone example that exhibits the same behavior :/

### CODE REVIEW

**Comment by jjallaire** [comment]
@kevinushey Should this be in the CRAN update as well?

@skeydan and @dfalbel, Does this fix an issue nasty enough that we should make sure that CRAN reticulate has the fix?

**Comment by skeydan** [comment]
I think so, yes. It does not crop up often but when it does, it's hard to sort out what's going on, especially if it's the first time you run into it.
Thanks!

**Comment by kevinushey** [comment]
I think we should take this for the CRAN update as well. I'll submit later after verifying the Conda JSON issue on all platforms.

**Comment by kevinushey** [comment]
CI failures are unrelated (looks like interim issue in devtools?)

**Pull request merged**
