### PR TITLE
address use of micromamba during initialization see #1378 and #1176

### LINKED ISSUE #1378: [Request] Include `^micromamba` in grepl check in `conda_binary` to allow direct use of micromamba
Including `^micromamba` here should allow reticulate to use micromamba in place of conda / mamba -- version checks are in different form, and some commands are missing, but I don't think this should be an issue for base functionality (i.e. activating a micromamba env for use)
https://github.com/rstudio/reticulate/blob/7a48c3a8466af1baa3ae0d431d30523f7a0a889c/R/conda.R#L511

### PR DESCRIPTION
**Pull request by t-kalinowski**
closes #1378, #1176 #1379

### CODE REVIEW

**Comment by t-kalinowski** [comment]
@zia1138, thanks so much for the PR. I started on modifying it to avoid the use of a micromamba global variable, but ran into an issue w/ micromamba. Specifically, I see an error message like:
```
$ '/home/tomasz/.local/bin/micromamba' activate '/home/tomasz/micromamba/envs/foo3'

'micromamba' is running as a subprocess and can't modify the parent shell.
Thus you must initialize your shell before using activate and deactivate.

    To initialize the current bash shell, run:
        $ eval "$(micromamba shell hook --shell=bash)"
    and then activate or deactivate with:
        $ micromamba activate
    
To automatically initialize all future (bash) shells, run:
    $ micromamba shell init --shell=bash --prefix=~/micromamba

Supported shells are {bash, zsh, csh, xonsh, cmd.exe, powershell, fish}.

critical libmamba Shell not initialized

```

After following the activation instructions I still see the same:
```bash
$ eval "$('/home/tomasz/.local/bin/micromamba' shell hook --shell=bash)"
tomasz@mule:~/micromamba/envs/foo3/conda-meta
$ '/home/tomasz/.local/bin/micromamba' activate '/home/tomasz/micromamba/envs/foo3'

'micromamba' is running as a subprocess and can't modify the parent shell.
Thus you must initialize your shell before using activate and deactivate.

    To initialize the current bash shell, run:
        $ eval "$(micromamba shell hook --shell=bash)"
    and then activate or deactivate with:
        $ micromamba activate
    
To automatically initialize all future (bash) shells, run:
    $ micromamba shell init --shell=bash --prefix=~/micromamba

Supported shells are {bash, zsh, csh, xonsh, cmd.exe, powershell, fish}.

critical libmamba Shell not initialized

```

We want to avoid using a global because
- there are multiple entry points for binding to python, not just `use_python()`
- users can manage conda environments without necessarily binding reticulate to a python binary.

**Comment by zia1138** [comment]
Thanks @t-kalinowski for considering this PR and for taking a first shot at removing the global. There might be an approach to address this without a global.  I will look into this as well.  

I think the issue that you see is because micromamba assumes that it is within $PATH for these shell hooks.  Try adding it to your path and see if it addresses the error.

**Comment by t-kalinowski** [comment]
Having `micromamba` on the PATH doesn't fix the issue. See this terminal session:
```bash
tomasz@mule:~
$ eval "$('/home/tomasz/.local/bin/micromamba' shell hook --shell=bash)"
tomasz@mule:~
$ '/home/tomasz/.local/bin/micromamba' activate '/home/tomasz/micromamba/envs/foo3'

'micromamba' is running as a subprocess and can't modify the parent shell.
Thus you must initialize your shell before using activate and deactivate.

    To initialize the current bash shell, run:
        $ eval "$(micromamba shell hook --shell=bash)"
    and then activate or deactivate with:
        $ micromamba activate
    
To automatically initialize all future (bash) shells, run:
    $ micromamba shell init --shell=bash --prefix=~/micromamba

Supported shells are {bash, zsh, csh, xonsh, cmd.exe, powershell, fish}.

critical libmamba Shell not initialized
tomasz@mule:~
$ eval "$(micromamba shell hook --shell=bash)"
Command '' not found, but can be installed with:
sudo apt install mailutils-mh  # version 1:3.14-1, or
sudo apt install mmh           # version 0.4-4
sudo apt install nmh           # version 1.7.1-11
sudo apt install termtris      # version 1.3-1ubuntu1
tomasz@mule:~
$ which micromamba
/home/tomasz/.local/bin/micromamba
tomasz@mule:~
$ micromamba activate foo3
Command '' not found, but can be installed with:
sudo apt install mailutils-mh  # version 1:3.14-1, or
sudo apt install mmh           # version 0.4-4
sudo apt install nmh           # version 1.7.1-11
sudo apt install termtris      # version 1.3-1ubuntu1
tomasz@mule:~
$ type micromamba
micromamba is a function
micromamba () 
{ 
    \local cmd="${1-__missing__}";
    case "$cmd" in 
        activate | deactivate)
            __mamba_activate "$@"
        ;;
        install | update | upgrade | remove | uninstall)
            __mamba_exe "$@" || \return;
            __mamba_reactivate
        ;;
        self-update)
            __mamba_exe "$@" || \return;
            if [ -f "$MAMBA_EXE.bkup" ]; then
                rm -i -f $MAMBA_EXE.bkup;
            fi
        ;;
        *)
            __mamba_exe "$@"
        ;;
    esac
}
tomasz@mule:~
```

**Comment by t-kalinowski** [comment]
I don't necessarily expect you to fix micromamba activation issues. If you're actively using micromamba, I would be happy to merge a minimal PR that enables reticulate to bind to it via `use_condaenv()` and `RETICULATE_PYTHON`, and avoids using a global. 

A simple approach might be to avoid the `conda_run2()` call during python initialization, and replacing it (for micromamba environments) with a bare system call to `micromamba run -n <name> '<python-expr-to-print-PATH>'`.

**Comment by t-kalinowski** [comment]
I confirmed that this works locally:
```R
options(reticulate.conda_binary = path.expand("~/.local/bin/micromamba"))
reticulate::use_condaenv("foo3")
```
where `foo3` was created at the terminal with
```bash
micromamba create -n 'foo3' python -c conda-forge
```

**Comment by zia1138** [comment]
Thanks @t-kalinowski for these changes. I can replicate the above with out errors, but I'm getting some errors and unexpected behavior on my end with other environments. I'll submit a PR with some more extensive testing when I get some free time.

**Pull request merged**
