### PR TITLE
Don't render vignette on CRAN

### LINKED ISSUE #1135: resolve vignette build issues
Seen on macOS and Windows.

```
checking re-building of vignette outputs ... [6s/8s] WARNING
Error(s) in re-building vignettes:
--- re-building ‘arrays.Rmd’ using rmarkdown
--- finished re-building ‘arrays.Rmd’

--- re-building ‘calling_python.Rmd’ using rmarkdown
--- finished re-building ‘calling_python.Rmd’

--- re-building ‘package.Rmd’ using rmarkdown
--- finished re-building ‘package.Rmd’

--- re-building ‘python_dependencies.Rmd’ using rmarkdown
--- finished re-building ‘python_dependencies.Rmd’

--- re-building ‘python_packages.Rmd’ using rmarkdown
--- finished re-building ‘python_packages.Rmd’

--- re-building ‘python_primer.Rmd’ using rmarkdown
Quitting from lines 155-176 (python_primer.Rmd)
Error: processing vignette 'python_primer.Rmd' failed with diagnostics:
invalid syntax (<string>, line 12)
--- failed re-building ‘python_primer.Rmd’

--- re-building ‘r_markdown.Rmd’ using rmarkdown
--- finished re-building ‘r_markdown.Rmd’

--- re-building ‘versions.Rmd’ using rmarkdown
--- finished re-building ‘versions.Rmd’

SUMMARY: processing the following file failed:
  ‘python_primer.Rmd’
```

cc: @t-kalinowski; this is why we do not run Python code on CRAN. :-)

### PR DESCRIPTION
**Pull request by t-kalinowski**
Closes #1135

### CODE REVIEW

**Comment by kevinushey** [comment]
Is pre-rendering the vignette locally an option?

**Comment by kevinushey** [comment]
I might be misunderstanding. I guess vignettes are _always_ built and submitted locally, but CRAN still tries to check that it can successfully rebuild those vignettes themselves (or run their R code) as part of R CMD check?

So this change would basically stop CRAN from trying to run our R code during checks. Does that sound right?

**Comment by t-kalinowski** [comment]
Just to make sure we're talking about the same thing, are you suggesting converting the vignette to a static document that doesn't evaluate code when CRAN builds it, (like the current Readme.md), or are you suggesting additional guards on the vignette render, like quarto's "freeze" parameter? I think you're suggesting the former.

You are right that with the approach in this PR, CRAN would not evaluate any of the code chunks. That's not ideal because then the output from the code chunks on the CRAN rendered vignette is also missing. Converting to a static document on the other hand is not great either, because we lose the ability to make easily make edits + and rerender in the future.

**Comment by kevinushey** [comment]
> Just to make sure we're talking about the same thing, are you suggesting converting the vignette to a static document that doesn't evaluate code when CRAN builds it, (like the current Readme.md), or are you suggesting additional guards on the vignette render, like quarto's "freeze" parameter? I think you're suggesting the former.

I'm thinking of the latter -- I'm hoping we can use the same `.Rmd` source, but have the final vignette that's published to CRAN be rendered locally and submitted as part of the package tarball. In other words, have the same local vignette workflow, but without the worry that CRAN might execute the vignette code and run into issues.

**Comment by kevinushey** [comment]
I also (out of some well-founded paranoia) don't like the idea that we're so obviously circumventing the CRAN check machinery here.

I'm going to prepare a separate candidate PR.

**Comment by kevinushey** [comment]
Superceded by https://github.com/rstudio/reticulate/commit/40bb05babb61f86d832f2b592e6fbdf2f69176be.

**Pull request closed without merging**
