### PR TITLE
Deprecated RangeIndex #762

### PR DESCRIPTION
**Pull request by tseppelt**

### CODE REVIEW

**Comment by kevinushey** [comment]
I think we need the PR to be backwards-compatible with older versions of `pandas` as well. Do older versions of Pandas also provide these members without the `_` prefix?

I wonder if we can introspect on the installed version of `pandas` in some way?

**Comment by tseppelt** [comment]
As far as I understand the ``pandas`` code, the new attributes were introduced in [this pull request](https://github.com/pandas-dev/pandas/pull/26581) in June 2019. Before June 2019 these members did not exist, I think.

**Comment by charlstown** [comment]
I have the same issue:
sys:1: FutureWarning: RangeIndex._* is deprecated and will be removed in a future version. Use RangeIndex.start instead
*start, stop step

The funny thing is, I didn't get the error at first but now every time I try to run py$dataframe I'm getting a fatal error.

**Comment by kevinushey** [comment]
```
>>> pandas.__version__
'0.24.2'
>>> index.start
AttributeError: 'RangeIndex' object has no attribute 'start'
```

So we definitely cannot just switch from `_start` to `start` -- we need to check which of the two exists and use that.

**Comment by kevinushey** [comment]
Fixed on master now.

**Pull request closed without merging**
