### PR TITLE
Feature/ensure gil

### LINKED ISSUE #208: reticulate + rpy2 sharing R process
Cannot get to work `rpy2` v 2.9.2 and `reticulate` v 1.6 with R v 3.4.3 and Python 3.5.5 (or 3.6.5) to share the same instance of R embedded process / engine instance.

context - reviewed these but still cannot make this work
https://github.com/rstudio/reticulate/issues/98
https://github.com/rstudio/reticulate/pull/104
https://github.com/rstudio/reticulate/issues/138

Environment
```
$ uname -a
Linux bigdata-vm 4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
Python and R setup with `conda` `environment.yml`

```
name: dev-ds
channels:
- r
- conda-forge
- anaconda 
- defaults
dependencies:
- conda-forge::python=3.5.5
- conda-forge::numpy=1.14.2
- conda-forge::pandas=0.22.0
# ==============
# R core
# ==============
- r-base=3.4.3
- r-magrittr=1.5
- r-reticulate    # is 1.3 but need 1.6* so re-installed manually from R
- r-dplyr=0.7.4
- r-dbi=0.7
- r-r6=2.2.2
- r-magrittr=1.5
- r-jsonlite=1.5
- r-dplyr=0.7.4
- r-purrr=0.2.4
- r-bindr=0.1
# ==============
# R application runtime 
# ==============
- r-readr=1.1.1
- r-config=0.2
- r-xml
- r-reshape2
- r-data.table
- r-forecast=8.2
- r-tseries
- nlopt
- r-nloptr=1.0.4
# ==============
# R application dev
# ==============
- r-git2r     # 0.20.0
- r-rcpp=0.12.14 # 0.12.16
- r-devtools=1.13.4
- r-testthat=2.0.0
- r-roxygen2
- r-sparklyr  # 0.7.0

# ==============
# Python core
# ==============
- pip:
  - rpy2==2.9.2 
```
Using R from under the `conda`  env:

```
library(reticulate)
reticulate::import("sys")
rpy2 <- import('rpy2')
robjects <- import('rpy2.robjects')
```
exists with _"R is already initialized"_ caused by last line.

From a Python script `some.py`

```
from rpy2.robjects import pandas2ri
from rpy2.robjects.packages import importr
import rpy2.robjects as robjects

def main():
    r = robjects.r

    x = robjects.IntVector(range(10))
    y = r.rnorm(10)

    import os, sys
    os.environ['RETICULATE_PYTHON'] = sys.executable

    robjects.r('library("reticulate")')
    robjects.r('reticulate::import("sys")')

    nested = robjects.r('''
    nested <- function() {
    
        library(reticulate)
        use_condaenv("dev-ds")
            
        reticulate::import("sys")
        robjects <- import('rpy2.robjects')
        robjects$r('R.version')  
     
        return (1)
    }
        
    nested       
    ''')

    n = nested()

    print(n)

if __name__ == "__main__":
    main()
```

getting this 

```
.../bin/python/conda3/envs/dev-ds/lib/python3.5/site-packages/rpy2/rinterface/__init__.py:145: RRuntimeWarning: 2: package ‘reticulate’ was built under R version 3.4.3 

  warnings.warn(x, RRuntimeWarning)
Traceback (most recent call last):
  File ".../some.py", line 63, in <module>
    main()
  File ".../some.py", line 40, in main
    robjects.r('reticulate::import("sys")')
  File "/.../bin/python/conda3/envs/dev-ds/lib/python3.5/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/../bin/python/conda3/envs/dev-ds/lib/python3.5/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/.../bin/python/conda3/envs/dev-ds/lib/python3.5/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ImportError: 'rpycall' is not a built-in module

Detailed traceback: 
  File "/development/bin/python/conda3/envs/dev-ds/lib/R/library/reticulate/python/rpytools/call.py", line 2, in <module>
    import rpycall

Segmentation fault (core dumped)

```

@randy3k kindly advise what is missing or wrong.

### PR DESCRIPTION
**Pull request by t-kalinowski**
closes #208

### CODE REVIEW

**Comment by kevinushey** [comment]
Was using `reticulate_types.h` + redefining `BEGIN_RCPP` not an option? I'm not a fan of needing to sprinkle `GILScope` everywhere.

**Comment by t-kalinowski** [comment]
I looked at it briefly, but it didn't seem safe to modify `BEGIN_RCPP` 
(please correct me if BEGIN_RCPP is meant to be overridden.). 

Also, not every rcpp exported function needs the Gil (or can even safely acquire it).

Defining our own C++ attribute and export wrapper would be a good approach too, but I opted for a scope object instead since it seemed simpler.

Happy to revise if you think it's worthwhile.

**Comment by eddelbuettel** [comment]
I think you can consider that.  We (as in 'Team Rcpp') did variants on it to do / do not include RNG setters and other things.  You should then locally consistent function interfaces in the compilation unit (as `compileAttributes` will update all of them, using the macro everywhere).

**Comment by t-kalinowski** [comment]
Do you know of an example of this type of approach I could use for reference?

**Comment by eddelbuettel** [comment]
Not from the top of my head from _another_ package but armed with a strong coffee or tea you probably figure how the `BEGIN` and `END` macros play along for general 'resource' (in the sense of eg the RNG) handling.  Doing it quasi-mutex for the gil may work.

https://github.com/RcppCore/Rcpp/blob/master/inst/include/Rcpp/macros/macros.h

Now of course I don;t immediatly see the RNG handling in there so I guess that is handed off to attributes...

**Comment by t-kalinowski** [comment]
So, trying something naive like redefining BEGIN_RCPP doesn't seem to work.

Defining this in `reticulate_types.h`:
```C
#define BEGIN_RCPP \
  BEGIN_RCPP       \
  GILScope gilscope;
```
gives:
```
  In file included from RcppExports.cpp:4:
   ./reticulate_types.h:91:9: warning: 'BEGIN_RCPP' macro redefined [-Wmacro-redefined]
   #define BEGIN_RCPP \
           ^
   /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include/Rcpp/macros/macros.h:49:9: note: previous definition is here
   #define BEGIN_RCPP                                                                               \
           ^
   RcppExports.cpp:17:1: error: unknown type name 'BEGIN_RCPP'
   BEGIN_RCPP
   ^
   ./reticulate_types.h:92:3: note: expanded from macro 'BEGIN_RCPP'
     BEGIN_RCPP       \
     ^
   RcppExports.cpp:17:1: error: expected ';' at end of declaration
   ./reticulate_types.h:93:12: note: expanded from macro 'BEGIN_RCPP'
     GILScope gilscope;

<...truncated...>
```

Digging into Rcpp it looks like RNG scope code is emitted [here](https://github.com/RcppCore/Rcpp/blob/101ad174199330032f82518a40dc14184a503826/src/attributes.cpp#L2890), which doesn't seem to expose any entry points for adding additional resources like GILScope.

The next step I see is to mask/wrap Rcpp::export(), but it feels like that's going down the wrong path.

Any suggestions are welcome.

**Comment by eddelbuettel** [comment]
For redefining a usual two-step is 

```
#ifdef foo 
#undef foo
#define foo
```

to avoid the redefinition warning.  Otherwise you seem to be on the right track but remember that these are macros and you need to get your special characters aligned.  I find that 'practising' in a one-off C(++) program (source) helps shake the cobwebs out.

**Comment by t-kalinowski** [comment]
Thanks @eddelbuettel,

The warning about a redefined macro isn't the main issue, doing the `#undef` and `#define` dance still leaves me with a failed build:

```
#define RETICULATE_GIL_BEGIN_RCPP   \
  BEGIN_RCPP;         \
  GILScope gilscope ;

#undef BEGIN_RCPP
#define BEGIN_RCPP RETICULATE_GIL_BEGIN_RCPP
#undef RETICULATE_GIL_BEGIN_RCPP
```

gives:
```
─  installing *source* package ‘reticulate’ ...
   ** using staged installation
   ** libs
   clang++ -arch arm64 -std=gnu++14 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include' -I/opt/R/arm64/include   -fPIC  -falign-functions=64 -Wall -g -O2  -Wall -pedantic -fdiagnostics-color=always -c RcppExports.cpp -o RcppExports.o
   RcppExports.cpp:17:1: error: unknown type name 'RETICULATE_GIL_BEGIN_RCPP'
   BEGIN_RCPP
   ^
   ./reticulate_types.h:98:20: note: expanded from macro 'BEGIN_RCPP'
   #define BEGIN_RCPP RETICULATE_GIL_BEGIN_RCPP
                      ^
   RcppExports.cpp:18:11: error: definition or redeclaration of 'RObject' not allowed inside a function
       Rcpp::RObject rcpp_result_gen;
       ~~~~~~^
   RcppExports.cpp:18:18: error: expected ';' at end of declaration
       Rcpp::RObject rcpp_result_gen;
                    ^
                    ;
   RcppExports.cpp:21:5: error: use of undeclared identifier 'rcpp_result_gen'
       rcpp_result_gen = Rcpp::wrap(write_stdout(text));
       ^
   RcppExports.cpp:22:12: error: use of undeclared identifier 'rcpp_result_gen'
       return rcpp_result_gen;
              ^
   RcppExports.cpp:23:1: error: expected unqualified-id
   END_RCPP
   ^
   /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include/Rcpp/macros/macros.h:99:18: note: expanded from macro 'END_RCPP'
   #define END_RCPP VOID_END_RCPP return R_NilValue;
                    ^
   /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include/Rcpp/macros/macros.h:62:5: note: expanded from macro 'VOID_END_RCPP'
       catch( Rcpp::internal::InterruptedException &__ex__) {                       
```

I'll try to work out the kinks in a skeleton package.

**Comment by eddelbuettel** [comment]
Sounds good. Work on a local skeleton to work out kinks is what I'd do too.  Also, and @kevinushey may correct me here, I don't think we've used it this way _from another package_ but conceivably we could open a well-designed door this way.  (For example `RcppArmadillo` has used something similar for a decade to "inject" R's RNG into Armadillo's header-only library.)

**Comment by t-kalinowski** [comment]
I think that what I was trying to do earlier is not possible. I wanted to redefine the `BEGIN_RCPP` macro by appending to the existing definition, but after some reading and reasoning I don't think the preprocessor lets you do that (though if you know of some delicate dance you can do to force a macro to be expanded inside a `#define` block on the first pass, please let me know).

Moving on, copy-pasting the existing `BEGIN_RCPP` definition and manually editing it gets past the preprocessor hurdle. This is what I have:

```C
#undef BEGIN_RCPP
#define BEGIN_RCPP                           \
  int rcpp_output_type = 0;                  \
  int nprot = 0;                             \
  (void)rcpp_output_type;                    \
  SEXP rcpp_output_condition = R_NilValue;   \
  (void)rcpp_output_condition;               \
  static SEXP stop_sym = Rf_install("stop"); \
  try {                                      \
    GILScope gilscope;

```

This compiles, but produces a segfault when loading. Now there needs to be some mechanism to opt-out of acquiring the GIL for the exported functions that can't safely acquire it yet (e.g., because Python is not initialized yet). 

Also, ideally it'd be nice if the `GILScope scope;` line was shown in the RcppExports.cpp adjacent to the RNG scope object, and not hidden in the `BEGIN_RCPP` macro, but `compileAttributes()` doesn't seem to have a nice built-in door for that.

**Comment by t-kalinowski** [comment]
I've pushed an implementation where `BEGIN_RCPP` is redefined to acquire the GIL in all exported functions. I've added a guard in the scope object to only acquire the GIL if python is already initialized (tracked by a new global bool).

All tests pass with this new approach, and `rpy2` can also successfully call into reticulate, just like in the prior commit.

Overall, I'm not sure if this is an improvement over the commit prior. 

It's nice to not have to sprinkle the "`GILScope scope;`" line, but it:
 -  still doesn't leave a nice way for an exported function to opt out of acquiring the GIL. 
 -  feels brittle because we've hard-coded `BEGIN_RCPP`, meaning that a future update to Rcpp that changes this definition would break us.

**Comment by eddelbuettel** [comment]
Six of one, half-a-dozen of another.  Sprinkling `GILscope` by hands risks forgetting it too.  These macros have probably not changed in a dozen years (and `git blame` could tell you more) so it's not clear this is a real risk.  Your call -- as a good software engineer you probably have to go to our shed now and invent a whole new preprocessor :wink:

**Comment by kevinushey** [comment]
> still doesn't leave a nice way for an exported function to opt out of acquiring the GIL.

That's true. Rcpp has some built-in facilities for disabling some of the auto-generated code, e.g. for RNGScope one might use:

```
// [[Rcpp::export(rng = false)]]
double myFunction(double input) {
    // ...code that never uses the
    // R random number generation...
}
```

But nothing user-extensible. You could still hack something like:

```
GILScope scope(__func__);
```

and then use the function name to decide if `GILScope` should actually do work. Pretty hacky though.

> feels brittle because we've hard-coded BEGIN_RCPP, meaning that a future update to Rcpp that changes this definition would break us.

FWIW I'm proposing we do something like:

```
#include <Rcpp.h>

#ifdef BEGIN_RCPP
# define RETICULATE_BEGIN_CPP_PREAMBLE BEGIN_RCPP
# undef BEGIN_RCPP
#else
# define RETICULATE_BEGIN_CPP_PREAMBLE
#endif

#define BEGIN_RCPP \
  RETICULATE_BEGIN_CPP_PREAMBLE \
  GILScope scope(__func__);
```

Which doesn't seem totally insane to me.

**Comment by kevinushey** [comment]
All that said, it's up to you to make the final call on what you feel will be easier to maintain / handle down the line. On the balance, I prefer the BEGIN_RCPP approach. One point in that approach's favor is that managing the GIL by default is probably the right call, and opting out could be done only on a case-by-case basis.

**Comment by t-kalinowski** [comment]
Thank you for the very helpful feedback!



> ```
> define RETICULATE_BEGIN_CPP_PREAMBLE BEGIN_RCPP
> ```

I don't think the preprocessor lets you do that. When `RETICULATE_BEGIN_CPP_PREAMBLE` gets expanded to `BEGIN_RCPP` on the first pass, and then by the 2nd pass `BEGIN_RCPP` doesn't expand to the original preamble anymore. 

I've been experimenting using `gcc -E` in https://godbolt.org to troubleshoot this.


I think I'll merge this PR as-is shortly (unless there are other suggestions).

FWIW, if there are any plans to expand RCPP in this direction, the code I would *want* to write is something like this:

Define an R callback that can live somewhere like `src/rcpp-exports-callbacks.R`. The call back receives a character vector of the autogenerated function, the function, name signature and types, and *any other arguments* that were passed to `//Rcpp::export(...)`

So that I could write
```C
// [[Rcpp::export(gil = FALSE)]]
double myFunction(double input) {
    // ...code that never uses the Python GIL
}
```

Then have a callback
```R
post_process_Rcpp_export <- function(name, sig, body, ..., gil = TRUE) {
  if(gil) 
    body <- c("GILScope gilscope;", body)
  body
}
```

**Comment by eddelbuettel** [comment]
We could support a hook similar to RNGScope.  A few months ago a patch added support for default arguments the signature generartor passes through to R.  But someone (you ?) has to sit down and write the patch.

**Comment by kevinushey** [comment]
> I don't think the preprocessor lets you do that. RETICULATE_BEGIN_CPP_PREAMBLE gets expanded to BEGIN_RCPP on the first pass, and then by the 2nd pass BEGIN_RCPP doesn't expand to the original preamble anymore.

There should be a way to make this happen; e.g. use an intermediate function to pass along the macro (and force its expansion):

```
#define BEGIN_RCPP_IMPL(PREAMBLE) \
  PREAMBLE \
  GILScope scope(__func__);

#define BEGIN_RCPP BEGIN_RCPP_IMPL(RETICULATE_BEGIN_CPP_PREAMBLE);
```

**Comment by kevinushey** [comment]
In particular, you cannot re-define a variable in terms of its previous definition; e.g. this does not work:

```
#define VAR a
#define VAR_OLD VAR
#define VAR_NEW VAR_OLD b
#undef VAR
#define VAR VAR_NEW
```

I had thought `VAR_OLD` would have been a "duplicate" definition of `VAR`, but instead they're more like "pointers" to the same content and `#undef VAR` forces both to lose their definitions.

**Comment by simone-romiti** [comment]
Hi all, I'm here because I got the following message when using the `rmarkdown::render` function:
```
The R package "reticulate" only fixed recently
    an issue that caused a segfault when used with rpy2:
    https://github.com/rstudio/reticulate/pull/1188
    Make sure that you use a version of that package that includes
    the fix.
```
I have unistalled `reticulate` and installed again in an `R` session as follows:
```
library(devtools)
install_github(repo="https://github.com/rstudio/reticulate/")
```
Unfortunately I still get the segmentation fault. What should I do? Thank you in advance.

**Comment by t-kalinowski** [comment]
Hi @simone-romiti Can you please open a new issue with a reprex?

**Pull request merged**
