### PR TITLE
[WIP] Remove wrapper.R as similar functionalities have been moved to {scaffolder}

### PR DESCRIPTION
**Pull request by terrytangyuan**
These functions are now being further developed in https://github.com/terrytangyuan/scaffolder instead.

Signed-off-by: terrytangyuan <terrytangyuan@gmail.com>

### CODE REVIEW

**Comment by kevinushey** [comment]
Since these functions are exported (and hence part of the API), I'd rather keep them but instead delegate to the associated functions in the scaffolder package. Does that sound reasonable?

**Comment by terrytangyuan** [comment]
Sounds good. I'll update this PR soon.

**Comment by terrytangyuan** [comment]
@kevinushey Actually scaffolder depends on reticulate and delegating would introduce circular dependencies so it does not seem feasible.

**Comment by kevinushey** [comment]
Fair enough. In that case I think it's fine to just remove them since they're unlikely to be commonly used functions; if anyone is affected I'll point them towards the scaffolder package. Sorry for the trouble!

**Comment by terrytangyuan** [comment]
No problem. Sounds good and feel free to ping me if anyone has encountered any issues as well.

**Comment by terrytangyuan** [comment]
@kevinushey The CI for scaffolder is failing though and I just realized that it needs to use `reticulate:::help_handler`. Would it be possible for `reticulate` to export `help_handler` and mark it as internal with `#' @keywords internal`?

**Comment by kevinushey** [comment]
That sounds fine to me.

**Comment by kevinushey** [comment]
I've exported the function as `py_help_handler` in the development version -- let me know if that's fine.

You can also access the internals with something like:

```
reticulate <- asNamespace("reticulate")
reticulate$help_handler(...)
```

if you need something that works in older versions of `reticulate`.

**Comment by terrytangyuan** [comment]
That works perfectly. Thanks!

**Pull request merged**
