### PR TITLE
call 'r_to_py', 'py_to_r' recursively for lists

### PR DESCRIPTION
**Pull request by kevinushey**
This PR makes two changes:

1. Now, we always convert R Dates to Python datetime objects. If users want to use NumPy datetime64 objects, they should explicitly work with times / POSIXcts. This is recommended for efficiency, and having type stability makes it easier to program against `reticulate`. (see also: https://github.com/rstudio/reticulate/issues/198)

2. For R list objects, calling `r_to_py()` will call `r_to_py()` on the inner elements recursively. This is a bit slower, but is necessary to ensure that e.g. lists of Date objects are coerced properly.

### CODE REVIEW

**Comment by terrytangyuan** [comment]
Would it better to do this recursively on Date objects? I am a little concerned that this will introduce overhead to downstream packages.

**Comment by kevinushey** [comment]
I don't quite understand what you mean.

**Comment by terrytangyuan** [comment]
Sorry I meant "would it better to do this recursively **only** on Date objects instead of doing this for lists items in general" .

**Comment by kevinushey** [comment]
Vectors of date objects aren't an issue:

```
> library(reticulate)
> dates <- rep(Sys.Date(), 3)
> r_to_py(dates)
['2018-05-11T00:00:00.000000000' '2018-05-11T00:00:00.000000000'
 '2018-05-11T00:00:00.000000000']
```

It's just for `list` objects where our only choice is to recursively visit each list element to figure out its type, and then do something sensible after learning about all the types. Or that's probably what you meant?

Recursively converting in this way would mean we could support conversions of things like this, though:

```
> r_to_py(list(1L, 2, "3", Sys.Date(), Sys.time()))
[1, 2.0, '3', datetime.date(2018, 5, 11), array(['2018-05-11T21:48:46.328669184'], dtype='datetime64[ns]')]
```

**Comment by kevinushey** [comment]
It also seems to me that if one uses Python lists + Python datetime objects, they're likely not placing efficiency as the top priority -- if someone absolutely needs efficient operations, then they're likely to stick with NumPy arrays (and so `datetime64`).

It's really tough to balance ergonomics + performance in this space :-/

**Comment by terrytangyuan** [comment]
Ok that makes sense to me now. Thanks for the clarification!

**Comment by kevinushey** [comment]
@jjallaire it's been a while since we submitted this PR but I think it's still worth taking. What do you think?

**Comment by jjallaire** [comment]
Will merge now. Could you commit a NEWS change to master and bump the development version?

**Pull request merged**
