### PR TITLE
avoid use of iterate in conversion of dict

### PR DESCRIPTION
**Pull request by kevinushey**
Part of https://github.com/rstudio/reticulate/issues/551.

### CODE REVIEW

**Comment by kevinushey** [comment]
Phew! Found the root cause -- we were accidentally decreasing the reference count on something that we intended to 'own'.

This should hopefully fix a whole class of segfaults that we might have been seeing the wild (ie anything built on top of `iterate()`).

**Comment by kevinushey** [comment]
@jjallaire can you sanity-check this diff? https://github.com/rstudio/reticulate/pull/552/commits/e0597983a41ad97c1e8607d0b1d043e96d52d3d7

I believe that if we want to construct a `py_ref()` here then we need to detach the PyObjectPtr; does that sound right?

**Comment by jjallaire** [comment]
Will want to take a thorough look at this (can probably do so tomorrow but if it's another day pls hold merging until I do)

**Comment by skeydan** [comment]
Wow, thank you so much Kevin!!  :-) :-) :-)

I'm of course no judge as to the fix, _but_, I haven't seen this (triggering 3 builds in a row ;-) for quite some time now:

image

**Comment by jjallaire** [comment]
It does indeed look like the semantics of `py_ref()` are that the object needs to have an active reference count on it that won't be freed by other means. In this case, that means the `PyObjectPtr` needs to forget about it so it fulfills this expectation (this `detach()`). In short, yes, this LGTM!

**Comment by langmm** [comment]
This is great, thank you!

**Comment by langmm** [comment]
One question, will these changes be pushed to CRAN/conda-forge and, if so, when will this occur? I'm a bit unfamiliar with the process on CRAN but noticed the version was published on 4/12/19, but conda-forge recipe was updated yesterday (7/17/19).

**Comment by kevinushey** [comment]
We're hoping to submit to CRAN soon; likely next week.

**Pull request merged**
