### PR TITLE
ensure length() returns a numeric value

### PR DESCRIPTION
**Pull request by kevinushey**
This PR ensures that `length.python.builtin.object()` always returns a numeric value, in line with what users would normally expect from the `length()` generic.

`py_len()` continues to emit an error for Python objects without a defined length.

### CODE REVIEW

**Comment by kevinushey** [comment]
Some considerations to keep in mind here:

- The notion of the length of an R object, and the notion of the length of a Python object, do not really map to the same meaning. In R, `length()` almost always means the vector-length of an object, whereas in Python the concept of length is more general (and many objects do not have a defined length).

- We should ensure that existing code continues to work; e.g. a lot of code might test for "empty-ness" with something like `if (length(x)) { ... }`. IMHO, it's important that we don't break code that might've been performing tests with a Python object here.

- In R, `length()` should virtually always return a numeric value; in Python, `len()` might give an error for objects without a defined length. IMHO, given that `length()` in R usually means the "vector-length" of an object, we should treat Python objects without `__len__` as scalar objects (vector-objects of length one), and so consider `length(x) == 1L` in that case.

**Comment by t-kalinowski** [comment]
Another alternative might be to return `NA_integer_` instead of `1L` when `PyObject_Size()` raises an exception because no `__len__()` method for the Python object exists.

It seems like the primary motivator for returning `1L` is to prevent introducing a breaking change to R code using the idiom `if(length(x))` as a shorthand for `if(!is.null(x) || !(is.vector(x) && identical(length(x), 0L)))`. This seems like a relatively minor and easy-to-fix breaking change, and considering the tradeoffs, I think it's worth it. (I've already implemented the required changes in {keras} and {tensorflow})

I think the proposed approach in this PR is not ideal because it leaves the meaning of `length` for python objects inconsistent: Sometimes `length(x)` will mean `` x$`__len__`() `` and sometimes it will mean `as.integer(inherits(x, "python.builtin.object"))`. This will make it hard to reason about code, and it also makes R code vulnerable to breaking changes from Python as Python objects gain `__len__()` methods.

I would prefer a consistent meaning for `length()` of Python objects. Two approaches, in order of preference:
1) `length()` is equivalent to `__len__()`, returns `NA_integer_` if the python object has no `__len__` method. 
2) `length()` always return `1L`. (there is precedence for this approach too. A close reading of `?length` has this snippet:
> ... All other objects (including functions) have length one.

**Comment by kevinushey** [comment]
I don't think we can use `NA` as the return value. A lot of existing code in the RStudio IDE calls `length()` on R objects in the environment pane (or, call functions that might call `length()`), and returning `NA` can cause issues. For example:

```
x <- structure(list(), class = "foo")
registerS3method("length", "foo", function(x) NA)
```

If I set this, then every time I refresh the Environment pane, I see this in the console:

```
Warning in str.default(val) : 'str.default': 'le' is NA, so taken as 0
```

Arguably, this is an issue that should be fixed in the IDE, but the problem is that many users will run with older versions of RStudio but the latest-available versions of R packages, and so this would effectively become a change that regressed behavior in the RStudio IDE.

Packages using `reticulate` which need better guarantees about the "real" length of a Python object can still use `py_len()`.

**Comment by kevinushey** [comment]
> length() always return 1L. (there is precedence for this approach too. A close reading of ?length has this snippet:

This would be consistent with the current behavior in that `length(<python.object>)` currently returns 2; that is, the length of the R environment hosting that object.

**Comment by kevinushey** [comment]
> This will make it hard to reason about code, and it also makes R code vulnerable to breaking changes from Python as Python objects gain __len__() methods.

For what it's worth, we do already treat some builtin Python objects specially, e.g.

```
> library(reticulate)
> x <- py_eval("[1, 2, 3]", convert = FALSE)
> length(x)
[1] 3
```

So it seems reasonable to me to extend this to all objects implementing `__len__`.

**Comment by t-kalinowski** [comment]
I think it's OK to return `1L`. It maximizes convenience and minimizes breaking changes. 👍

**Pull request merged**
