### PR TITLE
prefer Anaconda to python versions found in hard-coded locations

### PR DESCRIPTION
**Pull request by kevinushey**
Closes https://github.com/rstudio/reticulate/issues/1095.

cc: @t-kalinowski

### CODE REVIEW

**Comment by t-kalinowski** [comment]
I just tried this branch but I still get the same error

``` r
reticulate::py_install("tensorflow-deps", channel = "apple", method = "conda")
#> Error: one or more Python packages failed to install [error code 1]

## stderr output:
# DirectoryNotACondaEnvironmentError: The target directory exists, but it is not a conda environment.
# Use 'conda create' to convert the directory to a conda environment.
# target directory: /usr
```

Also, it binds to system python

``` r
reticulate::py_config()
#> python:         /usr/bin/python3
#> libpython:      /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/config-3.8-darwin/libpython3.8.dylib
#> pythonhome:     /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8:/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8
#> version:        3.8.9 (default, Aug  3 2021, 19:21:54)  [Clang 13.0.0 (clang-1300.0.29.3)]
#> numpy:           [NOT FOUND]
#> 
#> python versions found: 
#>  /usr/bin/python3
#>  /Users/tomasz/miniforge3/bin/python
```

The python at /usr/local is not found (installed via installer downloaded from www.python.org)
(my \~/.zprofile puts that python first on the path.
What’s best way to tell Rstudio I prefer that python and it should be first on the PATH?)

``` r
system("which -a python", intern = T)
#> [1] "/usr/bin/python"       "/usr/local/bin/python"
```

<sup>Created on 2021-12-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info  🥋  ✔️  🎪   ──────────────────────────────────────────────────
#>  hash: martial arts uniform, check mark, circus tent
#> 
#>  setting  value
#>  version  R version 4.1.2 (2021-11-01)
#>  os       macOS Monterey 12.0.1
#>  system   aarch64, darwin20
#>  ui       X11
#>  language (EN)
#>  collate  en_US.UTF-8
#>  ctype    en_US.UTF-8
#>  tz       America/New_York
#>  date     2021-12-04
#>  pandoc   2.16.1 @ /Applications/RStudio.app/Contents/MacOS/quarto/bin/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version   date (UTC) lib source
#>  cli           3.1.0     2021-10-27 [1] CRAN (R 4.1.1)
#>  digest        0.6.28    2021-09-23 [1] CRAN (R 4.1.1)
#>  evaluate      0.14      2019-05-28 [1] CRAN (R 4.1.0)
#>  fastmap       1.1.0     2021-01-25 [1] CRAN (R 4.1.0)
#>  fs            1.5.0     2020-07-31 [1] CRAN (R 4.1.0)
#>  glue          1.5.0     2021-11-07 [1] CRAN (R 4.1.1)
#>  here          1.0.1     2020-12-13 [1] CRAN (R 4.1.0)
#>  highr         0.9       2021-04-16 [1] CRAN (R 4.1.0)
#>  htmltools     0.5.2     2021-08-25 [1] CRAN (R 4.1.1)
#>  jsonlite      1.7.2     2020-12-09 [1] CRAN (R 4.1.0)
#>  knitr         1.36      2021-09-29 [1] CRAN (R 4.1.1)
#>  lattice       0.20-45   2021-09-22 [1] CRAN (R 4.1.2)
#>  magrittr      2.0.1     2020-11-17 [1] CRAN (R 4.1.0)
#>  Matrix        1.3-4     2021-06-01 [1] CRAN (R 4.1.2)
#>  png           0.1-7     2013-12-03 [1] CRAN (R 4.1.0)
#>  Rcpp          1.0.7     2021-07-07 [1] CRAN (R 4.1.0)
#>  reprex        2.0.1     2021-08-05 [1] CRAN (R 4.1.1)
#>  reticulate    1.22-9000 2021-12-04 [1] Github (rstudio/reticulate@d7c7338)
#>  rlang         0.4.12    2021-10-18 [1] CRAN (R 4.1.1)
#>  rmarkdown     2.11      2021-09-14 [1] CRAN (R 4.1.1)
#>  rprojroot     2.0.2     2020-11-15 [1] CRAN (R 4.1.0)
#>  rstudioapi    0.13      2020-11-12 [1] CRAN (R 4.1.0)
#>  sessioninfo   1.2.1     2021-11-02 [1] CRAN (R 4.1.2)
#>  stringi       1.7.5     2021-10-04 [1] CRAN (R 4.1.1)
#>  stringr       1.4.0     2019-02-10 [1] CRAN (R 4.1.1)
#>  withr         2.4.3     2021-11-30 [1] CRAN (R 4.1.2)
#>  xfun          0.28      2021-11-04 [1] CRAN (R 4.1.1)
#>  yaml          2.2.1     2020-02-01 [1] CRAN (R 4.1.0)
#> 
#>  [1] /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library
#> 
#> ─ Python configuration ───────────────────────────────────────────────────────
#>  python:         /usr/bin/python3
#>  libpython:      /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/config-3.8-darwin/libpython3.8.dylib
#>  pythonhome:     /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8:/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8
#>  version:        3.8.9 (default, Aug  3 2021, 19:21:54)  [Clang 13.0.0 (clang-1300.0.29.3)]
#>  numpy:           [NOT FOUND]
#>  
#>  python versions found: 
#>   /usr/bin/python3
#>   /Users/tomasz/miniforge3/bin/python
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

**Comment by kevinushey** [comment]
Does your miniforge Python installation have numpy installed?

**Comment by t-kalinowski** [comment]
No it does not at first on a fresh installation. After manually installing Numpy into the base env, `reticulate::py_install("tensorflow-deps", channel = "apple", method = "conda") succeeds, but it installs into the base environment at `~/miniforge3`. Should it be creating and installing into `~/miniforge3/envs/r-reticulate` environment here?

**Comment by kevinushey** [comment]
Good question -- honestly, I'm not sure. I had some conversations about @jjallaire re: making it easier for people to just use the base Anaconda environment, since that's likely going to be pre-loaded with everything the user needs installed.

In this world, we're less worried about users updating / installing things into the base environment...  but I worry a lot that installing or updating things in the base environment could ultimately break the Anaconda installation though.

An in-between solution would be to "clone" the base environment to `r-reticulate`, so that the environment has all the base goodies but installing things puts the user at less risk of breakage.

**Comment by t-kalinowski** [comment]
Honestly, I think it would be fine to say we don't have full support for managing (installing into) a miniforge python installation, or really, any self-managed python. I only started with miniforge because that's still the officially recommended way apple recommends installing Tensorflow: https://developer.apple.com/metal/tensorflow-plugin/

In general, it feels like there is much complexity introduced by trying to automate support for so many different python installations. Leaning towards a cleaner demarcation between responsibilities would simplify things: Either reticulate manages the python environment, or the user does. Having a partially-managed-by-both makes it so hard, because users can bring along so many different types of environments, it becomes difficult to automate (and as you mention, introduces risk that we break something the user manually configured).

**Comment by kevinushey** [comment]
Perhaps we should just always try to create an `r-reticulate` environment for the user if they haven't explicitly told us which copy of Python they want to use? That way, in the "reticulate is handling it for the user" case, we're doing our best to ensure that:

1. The user is working in a virtual / conda environment, and
2. We've installed whatever Python packages appear to be required.

**Comment by t-kalinowski** [comment]
That sounds good!
In a session where the user hasn't already explicitly pointed reticulate somewhere else, I generally understand the default of `envname = NULL` to be synonymous with `envname = "r-reticulate"`

**Pull request merged**
